### PR TITLE
generic CI test

### PR DESCRIPTION
**Pull request by axel-h**
Test with: https://github.com/seL4/camkes-vm-images/pull/7, https://github.com/seL4/camkes-vm-examples/pull/57

### CODE REVIEW

**Comment by axel-h** [comment]
@chrisguikema It seems to run the new test now, but there is an problem with the image name. Seems "zynqmp" is deep in the defaults. Either we clean this up to have a nice strong SOC/board differentiation or accept this as legacy for now to get things merged and have the board covered at least.

**Comment by chrisguikema** [comment]
Axel, thanks for doing this! I think we're gonna need @lsf37's opinion here. When you build for the ultra96, or the zcu102, or any variant of the ZUS+ platform, the resulting image is always `capdl-loader-image-arm-zynqmp`. However, it looks like the CI scripts expect the `capdl-loader-image-arm-<SPECIFIC_PLATFORM>` instead. 

https://github.com/seL4/ci-actions/blob/master/camkes-vm/build.py#L59

We may be able to add another piece of logic in the `get_platform` function here: https://github.com/seL4/ci-actions/blob/08c98dc30fac13105aec51124a38206ab572944c/seL4-platforms/platforms.py#L147

But like I said, I'll wait for Gerwin to respond here, since there are a few ways we can go about this.

**Comment by chrisguikema** [comment]
@axel-h can you rerun this? I added the `image_platform` which seems to exist solely to solve the problem we ran into.

**Comment by axel-h** [comment]
just push another dummy commit to my branch https://github.com/axel-h/camkes-vm/tree/patch-axel-ci-1 then this PR's CI runs again.

**Comment by chrisguikema** [comment]
I tried that, and it wouldn't let me push to your branch

**Comment by axel-h** [comment]
ok, i will do a dummy push then latwr. You could make a new draft PR from your own branch that tragets https://github.com/seL4/camkes-vm/tree/patch-axel-ci-base instead of master, that will also work.

**Comment by axel-h** [comment]
or well, removing and adding the `hw-test` label also triggered a re-run now

**Comment by lsf37** [comment]
The CI support is merged now.

**Pull request closed without merging**
